export const ALL_COUNTRIES = [
  "Afghanistan","Albania","Algeria","Andorra","Angola","Argentina","Armenia",
  "Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Belarus",
  "Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina",
  "Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia",
  "Cameroon","Canada","Cape Verde","Chad","Chile","China","Colombia","Comoros",
  "Costa Rica","Croatia","Cuba","Cyprus","Czech Republic","Denmark","Djibouti",
  "Dominican Republic","Ecuador","Egypt","El Salvador","Eritrea","Estonia",
  "Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia","Georgia",
  "Germany","Ghana","Greece","Guatemala","Guinea","Guyana","Haiti","Honduras",
  "Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel",
  "Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kosovo","Kuwait",
  "Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya",
  "Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia",
  "Maldives","Mali","Malta","Mauritania","Mauritius","Mexico","Moldova",
  "Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia",
  "Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria",
  "North Korea","North Macedonia","Norway","Oman","Pakistan","Panama",
  "Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal",
  "Qatar","Romania","Russia","Rwanda","Saudi Arabia","Senegal","Serbia",
  "Sierra Leone","Singapore","Slovakia","Slovenia","Somalia","South Africa",
  "South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden",
  "Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Togo",
  "Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Uganda","Ukraine",
  "United Arab Emirates","United Kingdom","United States","Uruguay",
  "Uzbekistan","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe"
];

export const DAILY_COUNTRIES = [
  { name: "Japan",        clue1: "An island nation in the Pacific Rim",                                    clue2: "Over 100 million people, yet one of the world's safest countries",   clue3: "Its currency shares a name with a Chinese unit of measurement",      clue4: "Cherry blossoms, bullet trains, and vending machines on every corner" },
  { name: "Brazil",       clue1: "The largest country in its hemisphere by far",                             clue2: "Home to the world's greatest river by water volume",                  clue3: "Its official language isn't Spanish",                                clue4: "Five-time winners of the world's most watched sporting event" },
  { name: "Egypt",        clue1: "A transcontinental country straddling two landmasses",                    clue2: "Over 90% of its people live on just 4% of the land",                  clue3: "Its currency is named after a unit once used across the Roman Empire",clue4: "Built structures so massive they remained the world's tallest for 3,800 years" },
  { name: "Norway",       clue1: "A thin sliver of a country stretching nearly 2,000km north to south",    clue2: "One of the least densely populated countries in Europe",               clue3: "Shares its currency name with a Scandinavian neighbour",              clue4: "Has more coastline per person than almost anywhere on Earth" },
  { name: "Kenya",        clue1: "Sits almost perfectly on the equator",                                    clue2: "Named after its highest mountain",                                     clue3: "Uses a currency named after an ancient Roman silver coin",            clue4: "Hosts the greatest wildlife migration on the planet every year" },
  { name: "Canada",       clue1: "Has more lakes than every other country combined",                        clue2: "The world's second largest country but ranks 37th in population",      clue3: "Shares its currency name — but not its value — with its neighbour",  clue4: "Famous for maple syrup, apologising, and extremely cold winters" },
  { name: "India",        clue1: "A peninsula that juts into the Indian Ocean",                             clue2: "Set to become the world's most populous country this decade",          clue3: "Its currency symbol was designed through a national competition in 2009", clue4: "The birthplace of four major world religions" },
  { name: "Argentina",    clue1: "The eighth largest country in the world",                                 clue2: "Has more psychoanalysts per capita than any other country",            clue3: "Its name comes from the Latin word for silver",                      clue4: "Home to both the highest peak and the lowest point in the Americas" },
  { name: "Germany",      clue1: "Borders nine different countries — more than almost any other",           clue2: "Reunified in 1990 after being divided for nearly half a century",      clue3: "Uses a currency shared with 19 other nations",                       clue4: "Inventor of the printing press, the car, and aspirin" },
  { name: "Morocco",      clue1: "The only African country with coastline on two different seas",           clue2: "A population of roughly 37 million — similar to California",           clue3: "Its currency name means 'one fifth' in Arabic",                      clue4: "Its blue city is one of the most photographed places in the world" },
  { name: "Australia",    clue1: "A country, a continent, and an island — all at once",                    clue2: "More wild camels than any other nation on Earth",                     clue3: "Its dollar was introduced in 1966, replacing a pound",               clue4: "More deadly creatures per square kilometre than anywhere else" },
  { name: "Turkey",       clue1: "The only country whose territory spans two continents",                   clue2: "One of the world's top five most visited countries",                   clue3: "Its currency collapsed dramatically in value between 2018 and 2022",  clue4: "Home to the world's oldest known temple, over 12,000 years old" },
  { name: "Switzerland",  clue1: "A small central European country with four official languages",           clue2: "Has not been at war with another country since 1815",                  clue3: "Its currency is one of the most stable and trusted in the world",    clue4: "Produces roughly half the world's luxury watches" },
  { name: "Mexico",       clue1: "Part of North America, but often culturally grouped elsewhere",           clue2: "The world's largest Spanish-speaking country by population",           clue3: "Its currency is the most traded in Latin America",                   clue4: "Home to more UNESCO World Heritage Sites than any country in the Americas" },
  { name: "Vietnam",      clue1: "An S-shaped country running 1,650km from north to south",                clue2: "The world's second largest exporter of coffee",                       clue3: "Its currency is one of the lowest-valued units in the world",        clue4: "Has a coastline stretching over 3,000km along the South China Sea" },
  { name: "Iceland",      clue1: "The most sparsely populated country in Europe",                          clue2: "Despite its name, it is actually quite green",                        clue3: "Has no army and hasn't fought a war since the Middle Ages",          clue4: "Sits directly on the boundary of two tectonic plates" },
  { name: "South Africa", clue1: "The southernmost country on its continent",                              clue2: "Has not one, not two, but three capital cities",                       clue3: "Its currency is named after the Boer republic that once dominated the region", clue4: "Released its most famous political prisoner in 1990 after 27 years" },
  { name: "Peru",         clue1: "One of only a few countries that contains part of the Amazon basin",     clue2: "Home to the world's highest navigable lake",                          clue3: "Its currency is named after a Peruvian sun deity",                   clue4: "Built a mountain citadel so hidden it wasn't known to the outside world until 1911" },
  { name: "Thailand",     clue1: "The only Southeast Asian country never colonised by a European power",   clue2: "Has over 60,000 Buddhist temples",                                    clue3: "Its currency translates literally as 'weight' in Thai",              clue4: "Known as the Land of Smiles — and the world capital of street food" },
  { name: "Poland",       clue1: "A flat country that has been invaded more than almost any other",        clue2: "The sixth most populous country in Europe",                           clue3: "Its currency is one of the oldest monetary units still in use today", clue4: "The birthplace of both Copernicus and Marie Curie" },
  { name: "Colombia",     clue1: "The only South American country with coastline on two oceans",           clue2: "The world's number one producer of a particular precious green gemstone", clue3: "Named after the explorer who never actually set foot on its soil",   clue4: "Produces 75% of the world's finest grade coffee" },
  { name: "Sweden",       clue1: "The largest country in Scandinavia by area",                             clue2: "Has more islands than it has bothered to count officially",            clue3: "Its currency shares a name with a Norwegian and Danish equivalent",  clue4: "Invented the safety match, the seatbelt, and the flat-pack furniture box" },
  { name: "Ethiopia",     clue1: "One of only two African countries never colonised",                      clue2: "Africa's second most populous country",                               clue3: "Has its own unique calendar — currently several years behind the rest of the world", clue4: "The origin of all coffee — and the country that consumes the most of it" },
  { name: "New Zealand",  clue1: "Two main islands sitting in the South Pacific",                          clue2: "The first country to give women the right to vote, in 1893",           clue3: "Its dollar is sometimes called the 'Kiwi' by currency traders",      clue4: "Has more sheep than people — by a ratio of about six to one" },
  { name: "Portugal",     clue1: "The westernmost country in mainland Europe",                             clue2: "Once controlled an empire spanning Africa, Asia, and South America",  clue3: "Uses the same currency as 18 of its continental neighbours",         clue4: "Invented a melancholic music genre that UNESCO listed as cultural heritage" },
  { name: "Indonesia",    clue1: "The world's largest archipelago nation",                                 clue2: "The fourth most populous country on Earth",                           clue3: "Its currency was once so devalued it had notes worth 100,000 units",  clue4: "Spread across 17,000 islands and three time zones" },
  { name: "Greece",       clue1: "A peninsula with thousands of islands scattered around it",              clue2: "Has been a member of the EU since 1981",                              clue3: "Its currency was replaced in 2002 after 2,700 years of use",         clue4: "Credited with inventing democracy, theatre, and the Olympics" },
  { name: "Nigeria",      clue1: "Africa's most populous nation by a significant margin",                  clue2: "Has over 500 distinct ethnic groups and languages",                   clue3: "Its currency is named after a former name for a major local river",   clue4: "The world's second largest film industry by number of films produced" },
  { name: "Chile",        clue1: "The longest country in the world from north to south",                   clue2: "One of South America's most economically stable nations",             clue3: "Its currency is one of the lowest-valued in South America",          clue4: "Produces nearly half of the world's copper supply" },
  { name: "Netherlands",  clue1: "About a third of its land sits below sea level",                         clue2: "The world's second largest exporter of food and agricultural products", clue3: "Uses the same currency as most of its European neighbours",          clue4: "Has more bicycles than people" },
];

export const CLUE_KEYS = [
  { key: "clue1", label: "Clue 1" },
  { key: "clue2", label: "Clue 2" },
  { key: "clue3", label: "Clue 3" },
  { key: "clue4", label: "Clue 4" },
];

export const MAX_GUESSES = 4;
