export const ALL_COUNTRIES = [
  "Afghanistan","Albania","Algeria","Andorra","Angola","Argentina","Armenia",
  "Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Belarus",
  "Belgium","Belize","Benin","Bhutan","Bolivia","Bosnia and Herzegovina",
  "Botswana","Brazil","Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia",
  "Cameroon","Canada","Cape Verde","Chad","Chile","China","Colombia","Comoros",
  "Costa Rica","Croatia","Cuba","Cyprus","Czech Republic","Denmark","Djibouti",
  "Dominican Republic","Ecuador","Egypt","El Salvador","Eritrea","Estonia",
  "Eswatini","Ethiopia","Fiji","Finland","France","Gabon","Gambia","Georgia",
  "Germany","Ghana","Greece","Guatemala","Guinea","Guyana","Haiti","Honduras",
  "Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Israel",
  "Italy","Jamaica","Japan","Jordan","Kazakhstan","Kenya","Kosovo","Kuwait",
  "Kyrgyzstan","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya",
  "Liechtenstein","Lithuania","Luxembourg","Madagascar","Malawi","Malaysia",
  "Maldives","Mali","Malta","Mauritania","Mauritius","Mexico","Moldova",
  "Monaco","Mongolia","Montenegro","Morocco","Mozambique","Myanmar","Namibia",
  "Nepal","Netherlands","New Zealand","Nicaragua","Niger","Nigeria",
  "North Korea","North Macedonia","Norway","Oman","Pakistan","Panama",
  "Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal",
  "Qatar","Romania","Russia","Rwanda","Saudi Arabia","Senegal","Serbia",
  "Sierra Leone","Singapore","Slovakia","Slovenia","Somalia","South Africa",
  "South Korea","South Sudan","Spain","Sri Lanka","Sudan","Suriname","Sweden",
  "Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Togo",
  "Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Uganda","Ukraine",
  "United Arab Emirates","United Kingdom","United States","Uruguay",
  "Uzbekistan","Venezuela","Vietnam","Yemen","Zambia","Zimbabwe"
];

export const DAILY_COUNTRIES = [
  { name: "Japan",        continent: "Asia",          population: "125 million",  capital: "Tokyo",        currency: "Japanese Yen",      landlocked: false, fact: "Home to Mount Fuji and famous for its cherry blossom season" },
  { name: "Brazil",       continent: "South America", population: "215 million",  capital: "Brasília",     currency: "Brazilian Real",     landlocked: false, fact: "Hosts the Amazon rainforest and the world's biggest carnival" },
  { name: "Egypt",        continent: "Africa",        population: "104 million",  capital: "Cairo",        currency: "Egyptian Pound",     landlocked: false, fact: "Ancient pyramids and the Nile River define its landscape" },
  { name: "Norway",       continent: "Europe",        population: "5.4 million",  capital: "Oslo",         currency: "Norwegian Krone",    landlocked: false, fact: "Famous for its dramatic fjords and the northern lights" },
  { name: "Kenya",        continent: "Africa",        population: "54 million",   capital: "Nairobi",      currency: "Kenyan Shilling",    landlocked: false, fact: "Home to the Maasai Mara and the Great Rift Valley" },
  { name: "Canada",       continent: "North America", population: "38 million",   capital: "Ottawa",       currency: "Canadian Dollar",    landlocked: false, fact: "The world's second largest country by total area" },
  { name: "India",        continent: "Asia",          population: "1.4 billion",  capital: "New Delhi",    currency: "Indian Rupee",       landlocked: false, fact: "Land of the Taj Mahal, the Ganges, and over 2000 languages" },
  { name: "Argentina",    continent: "South America", population: "45 million",   capital: "Buenos Aires", currency: "Argentine Peso",     landlocked: false, fact: "Famous for tango, world-class beef, and vast Patagonia" },
  { name: "Germany",      continent: "Europe",        population: "84 million",   capital: "Berlin",       currency: "Euro",               landlocked: false, fact: "Known for Oktoberfest, the Autobahn, and the Black Forest" },
  { name: "Morocco",      continent: "Africa",        population: "37 million",   capital: "Rabat",        currency: "Moroccan Dirham",    landlocked: false, fact: "Where the Sahara Desert meets the Atlas Mountains and Atlantic" },
  { name: "Australia",    continent: "Oceania",       population: "26 million",   capital: "Canberra",     currency: "Australian Dollar",  landlocked: false, fact: "Home to the Great Barrier Reef, kangaroos, and the Outback" },
  { name: "Turkey",       continent: "Asia/Europe",   population: "85 million",   capital: "Ankara",       currency: "Turkish Lira",       landlocked: false, fact: "Bridges two continents and was once home to ancient Troy" },
  { name: "Switzerland",  continent: "Europe",        population: "8.7 million",  capital: "Bern",         currency: "Swiss Franc",        landlocked: true,  fact: "Famous for its Alps, chocolate, cheese, and strict neutrality" },
  { name: "Mexico",       continent: "North America", population: "130 million",  capital: "Mexico City",  currency: "Mexican Peso",       landlocked: false, fact: "Ancient Mayan ruins meet one of the world's largest megacities" },
  { name: "Vietnam",      continent: "Asia",          population: "97 million",   capital: "Hanoi",        currency: "Vietnamese Dong",    landlocked: false, fact: "Famous for Ha Long Bay and its distinctive S-shaped coastline" },
  { name: "Iceland",      continent: "Europe",        population: "370,000",      capital: "Reykjavik",    currency: "Icelandic Króna",    landlocked: false, fact: "The land of fire and ice — volcanoes and glaciers coexist here" },
  { name: "South Africa", continent: "Africa",        population: "60 million",   capital: "Pretoria",     currency: "South African Rand", landlocked: false, fact: "Has three capital cities and Table Mountain as a landmark" },
  { name: "Peru",         continent: "South America", population: "33 million",   capital: "Lima",         currency: "Peruvian Sol",       landlocked: false, fact: "Home to Machu Picchu and the heartland of the Inca Empire" },
  { name: "Thailand",     continent: "Asia",          population: "70 million",   capital: "Bangkok",      currency: "Thai Baht",          landlocked: false, fact: "The Land of Smiles, known for golden temples and street food" },
  { name: "Poland",       continent: "Europe",        population: "38 million",   capital: "Warsaw",       currency: "Polish Zloty",       landlocked: false, fact: "Birthplace of Copernicus, Chopin, and home to pierogi" },
  { name: "Colombia",     continent: "South America", population: "51 million",   capital: "Bogotá",       currency: "Colombian Peso",     landlocked: false, fact: "García Márquez's homeland and one of the world's top coffee producers" },
  { name: "Sweden",       continent: "Europe",        population: "10 million",   capital: "Stockholm",    currency: "Swedish Krona",      landlocked: false, fact: "Land of ABBA, IKEA, and the midnight sun" },
  { name: "Ethiopia",     continent: "Africa",        population: "120 million",  capital: "Addis Ababa",  currency: "Ethiopian Birr",     landlocked: true,  fact: "Birthplace of coffee and home to one of the world's oldest Christian kingdoms" },
  { name: "New Zealand",  continent: "Oceania",       population: "5 million",    capital: "Wellington",   currency: "New Zealand Dollar", landlocked: false, fact: "Where Lord of the Rings was filmed — land of kiwis and rugby" },
  { name: "Portugal",     continent: "Europe",        population: "10 million",   capital: "Lisbon",       currency: "Euro",               landlocked: false, fact: "Once ruled a vast global empire; now famous for fado and custard tarts" },
  { name: "Indonesia",    continent: "Asia",          population: "275 million",  capital: "Jakarta",      currency: "Indonesian Rupiah",  landlocked: false, fact: "The world's largest archipelago — over 17,000 islands" },
  { name: "Greece",       continent: "Europe",        population: "10.7 million", capital: "Athens",       currency: "Euro",               landlocked: false, fact: "Birthplace of democracy, philosophy, and the Olympic Games" },
  { name: "Nigeria",      continent: "Africa",        population: "220 million",  capital: "Abuja",        currency: "Nigerian Naira",     landlocked: false, fact: "Africa's most populous nation and home to the booming Nollywood film industry" },
  { name: "Chile",        continent: "South America", population: "19 million",   capital: "Santiago",     currency: "Chilean Peso",       landlocked: false, fact: "One of the world's longest countries — desert in the north, glaciers in the south" },
  { name: "Netherlands",  continent: "Europe",        population: "17.9 million", capital: "Amsterdam",    currency: "Euro",               landlocked: false, fact: "Famous for windmills, tulips, and having more bikes than people" },
];

export const CLUE_KEYS = [
  { key: "continent",  label: "Continent"  },
  { key: "population", label: "Population" },
  { key: "capital",    label: "Capital"    },
  { key: "currency",   label: "Currency"   },
  { key: "landlocked", label: "Landlocked" },
  { key: "fact",       label: "Fun fact"   },
];

export const MAX_GUESSES = 6;